##
# AWS CloudFormation template targeted at deploying the ConfigToHdf
# lambda function and all of its supporting resources.
#
# https://aws.amazon.com/blogs/devops/passing-parameters-to-cloudformation-stacks-with-the-aws-cli-and-powershell/
#

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
Parameters:
  HeimdallUrl:
    Type: String
    AllowedPattern: \Ahttps?:\/\/.+
    Description: The Heimdall Server URL for use in ConfigToHdf.
  HeimdallApiUser:
    Type: String
    Description: The Heimdall Server username for use in ConfigToHdf.
  HeimdallApiPass:
    NoEcho: true
    Type: String
    Description: The Heimdall Server password for storing as a secret and for use in ConfigToHdf.
  HeimdallEvalTag:
    Type: String
    Description: The string to tag HDF results with in Heimdall.
  VpcId:
    Type: String
    Description: The VPC ID to associate with security groups and endpoints
  SubnetIdA:
    Type: String
    Description: The first VPC id to connect to the lambda.
  SubnetIdB:
    Type: String
    Description: The second VPC id to connect to the lambda.

Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secret.html
  # This secret needs to be pulled out of the YAML and be created separately 
  # before using this cloudformation template. 
  ConfigToHdfSecret:              
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: ConfigToHdfSecret
      Description: Contains a Heimdall Server password used in the ConfigToHdf lambda.
      SecretString: !Ref HeimdallApiPass

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html
  # https://docs.aws.amazon.com/secretsmanager/latest/userguide/vpc-endpoint-overview.html
  ConfigToHdfSecretVpcEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      # InvalidPolicyDocument. Why? I don't know - it's the same as the IAM role
      # PolicyDocument:
      #   Version: 2012-10-17
      #   Statement:
      #     - Effect: Allow
      #       Action:
      #         - secretsmanager:GetSecretValue
      #       Resource: 
      #         - !Ref ConfigToHdfSecret
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.secretsmanager'
      PrivateDnsEnabled: True
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      SecurityGroupIds:
        - !Ref ConfigToHdfSecretIngressSecurityGroup
      SubnetIds:
        - !Ref SubnetIdA
        - !Ref SubnetIdB

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html
  ConfigToHdfConfigVpcEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      # "Service com.amazonaws.us-gov-west-1.config only supports the full-access endpoint policy."
      # PolicyDocument:
      #   Version: 2012-10-17
      #   Statement:
      #     - Effect: Allow
      #       Action:
      #         - config:BatchGet*
      #         - config:Describe*
      #         - config:Get*
      #         - config:List*
      #         - config:Select*
      #       Resource: '*'
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.config'
      PrivateDnsEnabled: True
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      SecurityGroupIds:
        - !Ref ConfigToHdfConfigIngressSecurityGroup
      SubnetIds:
        - !Ref SubnetIdA
        - !Ref SubnetIdB

  # How to restrict access to only resources that are in the same security group:
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/security-group-rules-reference.html

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html
  # ONLY allow receiving traffic from ingress -> egress
  ConfigToHdfConfigIngressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ONLY allow traffic from egress to ingress
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: ConfigToHdfConfigIngressSecurityGroup
  ConfigToHdfHeimdallIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId:
        Fn::GetAtt:
        - ConfigToHdfConfigEgressSecurityGroup
        - GroupId
      GroupId:
        Fn::GetAtt:
        - ConfigToHdfConfigIngressSecurityGroup
        - GroupId

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html
  # ONLY allow traffic from ingress -> egress
  ConfigToHdfConfigEgressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ONLY allow traffic from egress to ingress
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: ConfigToHdfConfigEgressSecurityGroup
  ConfigToHdfHeimdallEgressRule:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      DestinationSecurityGroupId:
        Fn::GetAtt:
        - ConfigToHdfConfigIngressSecurityGroup
        - GroupId
      GroupId:
        Fn::GetAtt:
        - ConfigToHdfConfigEgressSecurityGroup
        - GroupId

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html
  # ONLY allow receiving traffic from ingress -> egress
  ConfigToHdfHeimdallIngressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ONLY allow traffic from egress to ingress
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: ConfigToHdfHeimdallIngressSecurityGroup
  ConfigToHdfHeimdallIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId:
        Fn::GetAtt:
        - ConfigToHdfHeimdallEgressSecurityGroup
        - GroupId
      GroupId:
        Fn::GetAtt:
        - ConfigToHdfHeimdallIngressSecurityGroup
        - GroupId

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html
  # ONLY allow traffic from ingress -> egress
  ConfigToHdfHeimdallEgressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ONLY allow traffic from egress to ingress
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: ConfigToHdfHeimdallEgressSecurityGroup
  ConfigToHdfHeimdallEgressRule:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      DestinationSecurityGroupId:
        Fn::GetAtt:
        - ConfigToHdfHeimdallIngressSecurityGroup
        - GroupId
      GroupId:
        Fn::GetAtt:
        - ConfigToHdfHeimdallEgressSecurityGroup
        - GroupId


  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html
  # ONLY allow receiving traffic from ingress -> egress
  ConfigToHdfSecretIngressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ONLY allow traffic from egress to ingress
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: ConfigToHdfSecretIngressSecurityGroup
  ConfigToHdfHeimdallIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId:
        Fn::GetAtt:
        - ConfigToHdfSecretEgressSecurityGroup
        - GroupId
      GroupId:
        Fn::GetAtt:
        - ConfigToHdfSecretIngressSecurityGroup
        - GroupId

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html
  # ONLY allow traffic from ingress -> egress
  ConfigToHdfSecretEgressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ONLY allow traffic from egress to ingress
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: ConfigToHdfSecretEgressSecurityGroup
  ConfigToHdfHeimdallEgressRule:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      DestinationSecurityGroupId:
        Fn::GetAtt:
        - ConfigToHdfSecretIngressSecurityGroup
        - GroupId
      GroupId:
        Fn::GetAtt:
        - ConfigToHdfSecretEgressSecurityGroup
        - GroupId

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  ConfigToHdfRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: ConfigToHdfRole
      Description: IAM Role for executing the ConfigToHdf lambda.
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies: 
        - PolicyName: AwsConfigReadAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - config:BatchGet*
                  - config:Describe*
                  - config:Get*
                  - config:List*
                  - config:Select*
                Resource: '*'
        - PolicyName: AwsSecretsManagerReadAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref ConfigToHdfSecret

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-code
  ConfigToHdf:
    Type: AWS::Lambda::Function
    Properties: 
      FunctionName: ConfigToHdf
      Description: Lambda capable of pulling AWS Config data, mapping to HDF, and pushing results to Heimdall Server API.
      PackageType: Zip
      Timeout: 300
      Runtime: ruby2.7
      MemorySize: 128
      Handler: lambda_function.lambda_handler
      Code: ../lambda/ConfigToHdf/function.zip
      Role: !GetAtt ConfigToHdfRole.Arn
      # These variables can be set as lambda environment variables or be
      # passed through the event data.
      Environment:
        Variables:
          HEIMDALL_URL: !Ref HeimdallUrl
          HEIMDALL_API_USER: !Ref HeimdallApiUser
          HEIMDALL_PASS_SECRET_NAME: 'ConfigToHdfSecret'
          HEIMDALL_EVAL_TAG: !Ref HeimdallEvalTag
          SECRETS_MANAGER_ENDPOINT: !Select [ 1, !GetAtt ConfigToHdfSecretVpcEndpoint.DnsEntries ]
          CONFIG_MANAGER_ENDPOINT: !Select [ 1, !GetAtt ConfigToHdfConfigVpcEndpoint.DnsEntries ]
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-vpcconfig.html
      VpcConfig:
        SecurityGroupIds:
          - !Ref ConfigToHdfHeimdallEgressSecurityGroup
          - !Ref ConfigToHdfSecretEgressSecurityGroup
          - !Ref ConfigToHdfConfigEgressSecurityGroup
        SubnetIds:
          - !Ref SubnetIdA
          - !Ref SubnetIdB

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html
  ConfigToHdfRule: 
    Type: AWS::Events::Rule
    Properties: 
      Name: ConfigToHdfRule
      Description: Event Rule schedule for triggering ConfigToHdf.
      ScheduleExpression: rate(24 hours)
      Targets: 
        - Arn: !GetAtt ConfigToHdf.Arn
          Id: "ConfigToHdf"

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: ConfigToHdf
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt ConfigToHdfRule.Arn
