# frozen_string_literal: true

source 'https://rubygems.org'

# gem 'aws-sdk-configservice', '~> 1'
gem 'aws-sdk-secretsmanager', '~> 1'
gem 'aws-sdk-lambda', '1.39.0'
# gem 'aws-xray-sdk', '0.11.4'
gem 'heimdall_tools'
gem 'multipart-post'

# gem 'byebug'

# gem 'heimdall_tools', git: 'https://github.com/jkufro/heimdall_tools.git', branch: 'awsConfig'
